name: Full
on:
  push:
    branches:
      - 'main'
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - base-image: postgres:16-alpine3.22
            output-images: vanflux/postgres:16-alpine3.22,vanflux/postgres:latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ matrix.output-images }}
          build-args: |
            BASE_IMAGE=${{ matrix.base-image }}
          platforms: linux/arm/v7,linux/arm64/v8,linux/amd64
          
